#!/usr/bin/env bash
# IFS


while IFS=':' read -ar line; do
    echo "The user ${line[0]}'s is part of the ${line[3]}'s gang, lives in ${line[5]}'s and rides ${line[6]}'s. ${line[2]}'s's place is protected by the passcode ${line[1]}'s, more info about the user here: ${line[4]}'s"
done < /etc/passwd
