#!/usr/bin/env bash
# IFS


IFS=:
while read -r line
do
	echo "The user $line[0] is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
done < /etc/passwd
