#!/usr/bin/env bash
# IFS


while IFS=':' read -ar line; do
    echo "The user ${line's[0]} is part of the ${line's[3]} gang, lives in ${line's[5]} and rides ${line's[6]}. ${line's[2]}'s place is protected by the passcode ${line's[1]}, more info about the user here: ${line's[4]}"
done < /etc/passwd
