#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5
#displays the visitor IP along with the HTTP status code from the Apache log file.

# Requirement:
#
# Format: IP HTTP_CODE
# in a list format
# See example
# You must use awk
# You are not allowed to use while, for, until and cut
awk '{print $1, $9}' apache-access.log
