#!/usr/bin/env bash
# Ordered from the greatest to the lowest number of occurrences
# See example
# You must use awk

awk '{print $1,$9}'''  apache-access.log | sort -V| uniq -c | sort -n | perl -e 'print reverse <>'
