#!/usr/bin/env bash
# gives you information about the school file.

exist=0
for file in *; do
    if [ "$file" == "school" ]
	then
	let exist=1
	echo "school file exists"
	if [ -s "$file" ]
	    then
	    echo "school file is not empty"
	else
	    echo "school file is empty"
	fi
	if [ -f "$file" ]
	    then
	    echo "school is a regular file"
	fi
    fi
done

if [ $exist -eq 0 ]
    then
    echo "school file does not exist"
fi

# exist=false
# isEmpty=true
# isFile=false


# for file in *; do
#     if [ "$file" == "school" ]
# 	then
# 	exist=true
# 	if [ -s "$file" ]
# 	    then
# 	    isEmpty=false
# 	fi
# 	if [ -f "$file" ]
# 	    then
# 	    isFile=true
# 	fi
#     fi
# done

# if $exist
# 	then
# 	echo "school file exists"

# 	if [ $isEmpty -eq 0 ]
# 	    then
# 	    echo "school file is not empty"
# 	else
# 	    echo "school file is empty"
# 	fi

# 	if $isFile
# 	    then
# 	    echo "school is a regular file"
# 	fi
# else
# 	echo "school file does not exist"
# fi
