#!/usr/bin/env bash
# gives you information about the school file.
exist=false
isEmpty=true
isFile=false
for file in *; do
    if [ "$file" == "school" ]
	then
	exist=true
	if [ -s "$file" ]
	    then
	    isEmpty=false
	fi
	if [ -f "$file" ]
	    then
	    isFile=true
	fi
    fi
done

if $exist
	then
	echo "school file exists"

	if ! $isEmpty
	    then
	    echo "school file is empty"
	else
	    echo "school file is not empty"
	fi

	if $isFile
	    then
	    echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
